// 60 realistic Indian tech jobs – local dataset for Job Notification Tracker
window.JOB_NOTIFICATION_TRACKER_JOBS = [
  {
    id: "j1",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹25k–₹45k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/amazon-sde-intern",
    description: "Join Amazon's India development center for a 6-month internship. You will work on real-world projects alongside experienced engineers, writing production code and participating in design reviews. Strong problem-solving and communication skills are essential."
  },
  {
    id: "j2",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Agile"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-tcs-get",
    description: "TCS GET program is designed for fresh graduates. You will undergo structured training and then be deployed on live projects in banking, retail, or technology domains. We look for strong fundamentals and willingness to learn."
  },
  {
    id: "j3",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/razorpay-junior-backend",
    description: "Build and maintain payment and banking APIs that power millions of transactions. You will work with senior engineers on scalability, observability, and clean code. Prior internship or project experience in backend development preferred."
  },
  {
    id: "j4",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=freshworks-frontend-intern",
    description: "Work on customer-facing products used by thousands of businesses. You will implement UI components, fix bugs, and collaborate with design and backend teams. Knowledge of React and modern JavaScript is required."
  },
  {
    id: "j5",
    title: "QA Intern",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "JIRA", "SQL"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹30k/month Internship",
    applyUrl: "https://www.naukri.com/job-listings-wipro-qa-intern",
    description: "Support our QA team in designing test cases, executing regression suites, and reporting defects. Exposure to automation tools and agile workflows. Suitable for candidates with a keen eye for detail and logical thinking."
  },
  {
    id: "j6",
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹18k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/swiggy-data-analyst-intern",
    description: "Analyze delivery and user behavior data to help improve operations and product decisions. You will write SQL queries, build dashboards, and present insights to stakeholders. Statistics or engineering background preferred."
  },
  {
    id: "j7",
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Microservices", "SQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-infosys-java-0-1",
    description: "Join our digital practice to develop and maintain enterprise Java applications. You will work on Spring Boot-based microservices and integrate with legacy systems. Training and mentorship provided for recent graduates."
  },
  {
    id: "j8",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/zoho-python-fresher",
    description: "Zoho builds products in-house from Chennai. We need freshers who love Python and want to build features used by millions. You will get hands-on experience with our codebase and product lifecycle from day one."
  },
  {
    id: "j9",
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Webpack"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=phonepe-react-1-3",
    description: "Build and own frontend experiences for India's largest payments app. You will work on performance, accessibility, and scalable component libraries. Strong React and JavaScript fundamentals with 1–3 years of experience required."
  },
  {
    id: "j10",
    title: "SDE Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Algorithms", "System Design", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/flipkart-sde-intern",
    description: "Flipkart's internship program gives you ownership of features used by millions. You will design, code, and deploy with guidance from mentors. We expect strong CS fundamentals and enthusiasm for large-scale systems."
  },
  {
    id: "j11",
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Cloud", "DevOps", "Agile"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-accenture-get",
    description: "Accenture's GET program trains you in full-stack development and cloud technologies. After training, you will join project teams serving global clients. We value learning agility and teamwork."
  },
  {
    id: "j12",
    title: "Junior Backend Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Haskell", "Java", "PostgreSQL", "AWS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/juspay-junior-backend",
    description: "Juspay powers payments for major apps. We use functional programming and rigorous engineering. You will work on reliability and performance of payment APIs. Interest in Haskell or FP is a plus."
  },
  {
    id: "j13",
    title: "Frontend Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "CSS", "Figma"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=cred-frontend-intern",
    description: "CRED's product is design-led and frontend-heavy. Interns work on real features, from components to animations. You need a portfolio or projects showing React and attention to UI/UX detail."
  },
  {
    id: "j14",
    title: "Data Analyst Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Power BI"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹35k/month Internship",
    applyUrl: "https://www.naukri.com/job-listings-paytm-data-intern",
    description: "Support analytics for payments and lending products. You will pull data, build reports, and help with A/B analysis. Strong SQL and basic Python or R required. Finance or analytics coursework is a plus."
  },
  {
    id: "j15",
    title: "Java Developer (0-1)",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "REST", "Oracle DB"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/capgemini-java-0-1",
    description: "Work on enterprise Java projects for global clients in banking and manufacturing. We provide certifications and on-the-job training. You should have a degree in CS or related field and knowledge of Java and databases."
  },
  {
    id: "j16",
    title: "React Developer (1-3)",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "React Native", "JavaScript", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/dunzo-react-1-3",
    description: "Dunzo's consumer and partner apps are built with React and React Native. You will own features end-to-end and work with product and design. Experience with mobile or PWA is beneficial."
  },
  {
    id: "j17",
    title: "SDE Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Cloud", "Machine Learning", "API"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹20k–₹40k/month Internship",
    applyUrl: "https://www.naukri.com/job-listings-ibm-sde-intern",
    description: "IBM India Labs offers internships in AI, cloud, and enterprise software. You will contribute to open source or internal tools with mentorship. Interest in emerging tech and good programming skills expected."
  },
  {
    id: "j18",
    title: "Graduate Engineer Trainee",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: [".NET", "C#", "SQL Server", "Azure"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=cognizant-get",
    description: "Cognizant's GET program focuses on Microsoft stack and cloud. You will be trained and then assigned to projects in healthcare, retail, or financial services. We welcome engineering graduates with a passion for technology."
  },
  {
    id: "j19",
    title: "Junior Backend Developer",
    company: "Slice",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Go", "PostgreSQL", "Kafka", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/slice-junior-backend",
    description: "Slice is a fintech building card and payment products. Backend is in Go; we value clean code and system thinking. You will build APIs and event-driven services. Prior Go or backend internship is a plus."
  },
  {
    id: "j20",
    title: "Python Developer (Fresher)",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Linux", "Scripting"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-oracle-python-fresher",
    description: "Oracle India develops database and cloud products. Freshers join our tools and automation teams, writing Python for internal platforms. Strong fundamentals in programming and databases are required."
  },
  {
    id: "j21",
    title: "Frontend Intern",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["JavaScript", "React", "API", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹25k–₹45k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/postman-frontend-intern",
    description: "Postman's product is used by millions of developers. Interns work on the web app: UI components, API explorer, and collaboration features. You need solid JavaScript and React; familiarity with APIs is a plus."
  },
  {
    id: "j22",
    title: "QA Intern",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Test Automation", "Selenium", "Java", "CI/CD"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹18k–₹32k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=sap-qa-intern",
    description: "SAP's quality engineering team ensures our enterprise software meets high standards. You will write and maintain automated tests and work in agile sprints. CS or IT background with interest in QA required."
  },
  {
    id: "j23",
    title: "Data Analyst Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Looker", "Statistics"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/razorpay-data-intern",
    description: "Analyze payment and merchant data to drive product and risk decisions. You will build dashboards, run experiments, and present to stakeholders. Strong SQL and basic Python or R; familiarity with BI tools preferred."
  },
  {
    id: "j24",
    title: "Java Developer (0-1)",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Kafka", "Kubernetes"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/job-listings-dell-java-0-1",
    description: "Dell's India R&D builds infrastructure and cloud software. You will develop microservices and event-driven systems. We look for 0–1 year experience or strong internship in Java and distributed systems."
  },
  {
    id: "j25",
    title: "React Developer (1-3)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/zoho-react-1-3",
    description: "Zoho has 50+ products built in-house. React developers own modules in CRM, Mail, or Analytics. You need 1–3 years of React experience and the ability to work in a product-focused, long-term codebase."
  },
  {
    id: "j26",
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C#", "Azure", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/microsoft-sde-intern-india",
    description: "Microsoft IDC offers internships across Azure, Office, and gaming. You will ship code to production with mentorship from senior engineers. We expect strong problem-solving and familiarity with at least one major language."
  },
  {
    id: "j27",
    title: "Graduate Engineer Trainee",
    company: "Wipro",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Testing"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-wipro-get",
    description: "Wipro's GET program trains you in full-stack and testing. After induction, you join projects in BFSI, healthcare, or retail. We value communication skills and willingness to work in varied technologies."
  },
  {
    id: "j28",
    title: "Junior Backend Developer",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "Redis", "MySQL"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=sharechat-junior-backend",
    description: "ShareChat and Moj serve millions of users. Backend team builds APIs and services for content, feed, and ads. You need 0–1 year experience in Python or similar; scale and performance mindset is important."
  },
  {
    id: "j29",
    title: "Frontend Intern",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "Testing", "Web APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹22k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/browserstack-frontend-intern",
    description: "BrowserStack helps developers test on real devices. Interns work on the dashboard and documentation UI. Strong React and JavaScript; interest in developer tools and testing is a plus."
  },
  {
    id: "j30",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Statistics"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹20k–₹38k/month Internship",
    applyUrl: "https://www.naukri.com/job-listings-flipkart-data-intern",
    description: "Support analytics for e-commerce: demand, supply, and customer behavior. You will query large datasets and build reports. Engineering or statistics background with SQL and Python preferred."
  },
  {
    id: "j31",
    title: "Python Developer (Fresher)",
    company: "Thoughtworks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "TDD", "Agile", "Clean Code"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/thoughtworks-python-fresher",
    description: "Thoughtworks hires freshers into our developer community. You will work on client projects with pair programming and TDD. We look for passion for craft, learning, and diversity of thought."
  },
  {
    id: "j32",
    title: "React Developer (1-3)",
    company: "CleverTap",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "GraphQL", "D3.js"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=clevertap-react-1-3",
    description: "CleverTap's dashboard is used by marketers worldwide. You will build React components and data visualizations. Experience with charts or analytics UIs and TypeScript is preferred."
  },
  {
    id: "j33",
    title: "SDE Intern",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "React", "AWS", "Databases"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹28k–₹48k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/intuit-sde-intern",
    description: "Intuit India works on TurboTax, QuickBooks, and Mailchimp. Interns contribute to features used by millions. We value strong fundamentals, ownership, and collaboration. CS or related degree required."
  },
  {
    id: "j34",
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Angular", "SQL", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-lti-get",
    description: "LTI's GET program trains you in digital technologies and then deploys you on global projects. We look for engineering graduates with good academics and readiness to learn and travel if needed."
  },
  {
    id: "j35",
    title: "Junior Backend Developer",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "WebRTC"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/unacademy-junior-backend",
    description: "Unacademy's backend powers live classes and content delivery. You will work on APIs and real-time systems. Node.js and database experience from projects or internship preferred."
  },
  {
    id: "j36",
    title: "QA Intern",
    company: "Accenture",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "JIRA", "SQL"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹28k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=accenture-qa-intern",
    description: "Support QA on enterprise and digital projects. You will create test cases, execute tests, and log defects. We welcome freshers with logical thinking and basic knowledge of testing concepts."
  },
  {
    id: "j37",
    title: "Java Developer (0-1)",
    company: "HCL Tech",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "Oracle"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-hcl-java-0-1",
    description: "HCL hires junior Java developers for product and service projects. You will work on enterprise applications with Spring and SQL. Training provided; we expect solid OOP and database basics."
  },
  {
    id: "j38",
    title: "React Developer (1-3)",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "PWA", "Performance"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/swiggy-react-1-3",
    description: "Swiggy's web and mobile web experiences are critical for growth. You will build responsive, performant UIs. Experience with React, state management, and cross-browser compatibility required."
  },
  {
    id: "j39",
    title: "SDE Intern",
    company: "Goldman Sachs",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Algorithms", "Finance Basics"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/goldman-sachs-sde-intern",
    description: "Engineering interns at Goldman Sachs work on platforms that power global markets. You will get exposure to low-latency systems and financial workflows. Strong CS fundamentals and interest in finance preferred."
  },
  {
    id: "j40",
    title: "Data Analyst Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "BigQuery", "Tableau"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹22k–₹42k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=phonepe-data-intern",
    description: "Analyze transaction and user data to support product and business decisions. You will work with large datasets and build dashboards. SQL and Python required; exposure to analytics or ML is a plus."
  },
  {
    id: "j41",
    title: "Frontend Intern",
    company: "Zeta",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "CSS", "Webpack"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "₹20k–₹38k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/zeta-frontend-intern",
    description: "Zeta builds card and banking tech. Interns work on internal and client-facing dashboards. Strong React and TypeScript; attention to accessibility and design consistency is valued."
  },
  {
    id: "j42",
    title: "Junior Backend Developer",
    company: "Deutsche Bank",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Kafka", "Oracle"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/job-listings-deutsche-junior-backend",
    description: "Deutsche Bank's Pune technology center builds trading and risk platforms. You will work on Java microservices and messaging. We provide training; 0–1 year experience or strong internship in Java required."
  },
  {
    id: "j43",
    title: "Python Developer (Fresher)",
    company: "InMobi",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Data Pipelines", "SQL", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/inmobi-python-fresher",
    description: "InMobi's ad tech runs on data pipelines and ML. Freshers join our data engineering and tools teams. Python, SQL, and scripting skills required; interest in data or ML is a plus."
  },
  {
    id: "j44",
    title: "React Developer (1-3)",
    company: "Lenskart",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Next.js", "JavaScript", "REST"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=lenskart-react-1-3",
    description: "Lenskart's e-commerce and try-on experiences are built with React and Next.js. You will own frontend features and work with design and backend. 1–3 years of React experience required."
  },
  {
    id: "j45",
    title: "SDE Intern",
    company: "Directi",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["JavaScript", "Node.js", "React", "MongoDB"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹45k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/directi-sde-intern",
    description: "Directi (Radix, Ring) offers remote internships in full-stack development. You will work on product features and internal tools. Strong JavaScript and willingness to learn quickly required."
  },
  {
    id: "j46",
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Automation", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-tech-mahindra-get",
    description: "Tech Mahindra's GET program trains you in digital engineering and then assigns you to client projects. We look for engineering graduates with good communication and adaptability."
  },
  {
    id: "j47",
    title: "Java Developer (0-1)",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "SAP Cloud", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/sap-java-0-1",
    description: "SAP India develops cloud and enterprise products. Junior Java developers work on microservices and integrations. We provide SAP-specific training; strong Java and Spring basics required."
  },
  {
    id: "j48",
    title: "QA Intern",
    company: "Mindtickle",
    location: "Pune",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Selenium", "API Testing", "Postman", "JIRA"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "₹18k–₹32k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=mindtickle-qa-intern",
    description: "Mindtickle's QA team ensures quality of our sales enablement platform. Interns help with automation and API testing. CS or IT background with interest in test automation preferred."
  },
  {
    id: "j49",
    title: "Data Analyst Intern",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Visualization"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹18k–₹36k/month Internship",
    applyUrl: "https://www.naukri.com/job-listings-ola-data-intern",
    description: "Support analytics for ride-hailing and electric mobility. You will work with supply, demand, and ops data. Strong SQL and basic Python; ability to present insights clearly is important."
  },
  {
    id: "j50",
    title: "React Developer (1-3)",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "AWS", "Accessibility"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/amazon-react-1-3",
    description: "Amazon's consumer and internal tools use React extensively. You will build accessible, scalable UIs. We expect 1–3 years of frontend experience and focus on performance and customer obsession."
  },
  {
    id: "j51",
    title: "Junior Backend Developer",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=groww-junior-backend",
    description: "Groww is a leading investment platform. Backend team builds APIs for trading and user management. You need 0–1 year in Java or similar; understanding of security and compliance is a plus."
  },
  {
    id: "j52",
    title: "SDE Intern",
    company: "Atlassian",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Java", "React", "REST", "Databases"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/atlassian-sde-intern",
    description: "Atlassian India works on Jira, Confluence, and Trello. Interns contribute to features used by teams globally. We value collaboration, ownership, and strong programming fundamentals."
  },
  {
    id: "j53",
    title: "Python Developer (Fresher)",
    company: "HackerRank",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=hackerrank-python-fresher",
    description: "HackerRank builds assessment and interview tools. Freshers work on backend services and integrations. Python and web development basics required; interest in developer tools is a plus."
  },
  {
    id: "j54",
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "CSS", "Design Systems"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹22k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/razorpay-frontend-intern",
    description: "Razorpay's dashboard and checkout experiences need to be fast and reliable. Interns work on components and pages with senior developers. React and TypeScript; eye for detail required."
  },
  {
    id: "j55",
    title: "Java Developer (0-1)",
    company: "Walmart Global Tech",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Kafka", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/job-listings-walmart-java-0-1",
    description: "Walmart India tech builds e-commerce and supply chain systems. Junior Java developers work on microservices and event-driven architecture. Training provided; we expect solid Java and CS fundamentals."
  },
  {
    id: "j56",
    title: "React Developer (1-3)",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Animation", "Performance"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/cred-react-1-3",
    description: "CRED's product is design-forward. React developers own features from concept to ship, with focus on animation and performance. 1–3 years of React; portfolio showing polish is preferred."
  },
  {
    id: "j57",
    title: "Data Analyst Intern",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Redash", "A/B Testing"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹20k–₹38k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=zomato-data-intern",
    description: "Zomato's data team supports product, growth, and operations. You will run analyses and build dashboards. Strong SQL and Python; familiarity with experimentation or metrics is a plus."
  },
  {
    id: "j58",
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Testing", "Agile"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job-listings-infosys-get-mysore",
    description: "Infosys Mysore training center runs one of the largest GET programs. You will undergo residential training and then be assigned to projects. We welcome engineering graduates from recognized institutions."
  },
  {
    id: "j59",
    title: "Junior Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Kotlin", "PostgreSQL", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/phonepe-junior-backend",
    description: "PhonePe's backend handles billions of transactions. You will work on reliability, APIs, and data pipelines. 0–1 year in Java or Kotlin; understanding of distributed systems is a plus."
  },
  {
    id: "j60",
    title: "SDE Intern",
    company: "LinkedIn",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "ML Basics"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/linkedin-sde-intern-india",
    description: "LinkedIn India works on talent, learning, and sales products. Interns contribute to backend or ML pipelines. We look for strong problem-solving, collaboration, and interest in professional networks."
  }
];
